AnzalaSyed 
F20605001
Lab 10


Task: Based on the Genetic algorithm, in which the steps of have explained. Every student needs to
implement the Genetic Algorithm in Python.

In [4]:
import random

# Function to initialize a population of individuals
def initialize_population(population_size, chromosome_length):
    return [[random.choice([0, 1]) for _ in range(chromosome_length)] for _ in range(population_size)]

# Function to calculate the fitness score of an individual (customize for your problem)
def calculate_fitness(individual):
    # Add your fitness calculation logic here
    return sum(individual)

# Selection operator - Roulette Wheel Selection
def select_parents(population, fitness_scores):
    total_fitness = sum(fitness_scores)
    probabilities = [score / total_fitness for score in fitness_scores]
    parents = random.choices(population, probabilities, k=2)
    return parents

# Crossover operator - Single-point crossover
def crossover(parent1, parent2):
    crossover_point = random.randint(1, len(parent1) - 1)
    child = parent1[:crossover_point] + parent2[crossover_point:]
    return child

# Mutation operator - Flip a random bit
def mutate(individual, mutation_rate):
    return [bit ^ (random.random() < mutation_rate) for bit in individual]

# Main Genetic Algorithm function
def genetic_algorithm(population_size, chromosome_length, generations, mutation_rate):
    population = initialize_population(population_size, chromosome_length)

    for generation in range(generations):
        fitness_scores = [calculate_fitness(individual) for individual in population]

        # Select parents, perform crossover, and apply mutation to create a new population
        new_population = []
        for _ in range(population_size):
            parents = select_parents(population, fitness_scores)
            child = mutate(crossover(parents[0], parents[1]), mutation_rate)
            new_population.append(child)

        population = new_population

        # Optionally, you can track and print the best individual in each generation
        best_individual = population[fitness_scores.index(max(fitness_scores))]
        print(f"Generation {generation + 1}: Fitness = {max(fitness_scores)}, Best Individual = {best_individual}")

    # Return the best individual from the final population
    return max(population, key=calculate_fitness)

if __name__ == "__main__":
    # Example usage
    population_size = 10
    chromosome_length = 10
    generations = 50
    mutation_rate = 0.01

    result = genetic_algorithm(population_size, chromosome_length, generations, mutation_rate)

    print(f"\nFinal Result: {result}")


Generation 1: Fitness = 7, Best Individual = [1, 0, 0, 1, 1, 0, 1, 0, 1, 1]
Generation 2: Fitness = 6, Best Individual = [1, 0, 1, 0, 0, 1, 0, 1, 1, 1]
Generation 3: Fitness = 7, Best Individual = [1, 0, 0, 1, 1, 0, 1, 0, 1, 1]
Generation 4: Fitness = 8, Best Individual = [1, 0, 1, 0, 0, 1, 0, 1, 1, 1]
Generation 5: Fitness = 7, Best Individual = [1, 0, 1, 0, 1, 0, 1, 0, 1, 1]
Generation 6: Fitness = 8, Best Individual = [0, 0, 1, 0, 1, 1, 0, 1, 1, 1]
Generation 7: Fitness = 6, Best Individual = [1, 0, 1, 0, 0, 1, 0, 1, 1, 1]
Generation 8: Fitness = 7, Best Individual = [1, 0, 1, 0, 0, 1, 0, 1, 1, 1]
Generation 9: Fitness = 7, Best Individual = [1, 0, 1, 0, 1, 0, 1, 1, 1, 1]
Generation 10: Fitness = 7, Best Individual = [1, 0, 1, 0, 1, 1, 0, 1, 1, 1]
Generation 11: Fitness = 7, Best Individual = [1, 0, 1, 0, 0, 1, 1, 0, 1, 1]
Generation 12: Fitness = 8, Best Individual = [1, 0, 1, 0, 0, 1, 1, 0, 1, 1]
Generation 13: Fitness = 8, Best Individual = [1, 0, 1, 0, 0, 1, 1, 0, 1, 1]
Generati

In [3]:
import numpy as np

# Define the parameters
population_size = 10
chromosome_length = 8
mutation_rate = 0.1
generations = 100

# Function to initialize the population
def initialize_population(population_size, chromosome_length):
    return np.random.randint(2, size=(population_size, chromosome_length))

# Function to calculate the fitness of each individual
def calculate_fitness(population):
    return np.sum(population, axis=1)

# Function to perform selection based on roulette wheel selection
def select_parents(population, fitness):
    probabilities = fitness / np.sum(fitness)
    selected_indices = np.random.choice(np.arange(population_size), size=population_size, p=probabilities)
    return population[selected_indices]

# Function to perform crossover (single-point crossover)
def crossover(parents):
    crossover_point = np.random.randint(1, chromosome_length - 1)
    children = np.empty_like(parents)

    for i in range(0, population_size, 2):
        children[i, :crossover_point] = parents[i, :crossover_point]
        children[i, crossover_point:] = parents[i + 1, crossover_point:]
        children[i + 1, :crossover_point] = parents[i + 1, :crossover_point]
        children[i + 1, crossover_point:] = parents[i, crossover_point:]

    return children

# Function to perform mutation
def mutate(children):
    mutation_mask = np.random.rand(population_size, chromosome_length) < mutation_rate
    children ^= mutation_mask
    return children

# Main genetic algorithm loop
population = initialize_population(population_size, chromosome_length)

for generation in range(generations):
    fitness = calculate_fitness(population)
    parents = select_parents(population, fitness)
    children = crossover(parents)
    children = mutate(children)

    # Replace old population with new population
    population = children

# Print the final population and its fitness
final_fitness = calculate_fitness(population)
print("Final Population:")
print(population)
print("Final Fitness:")
print(final_fitness)


Final Population:
[[0 1 1 1 0 1 0 0]
 [0 1 1 1 0 0 1 0]
 [0 1 1 1 1 0 0 0]
 [1 0 1 1 0 1 1 1]
 [1 1 1 1 1 1 0 1]
 [1 1 0 0 1 1 1 1]
 [0 0 1 1 0 1 1 1]
 [0 1 1 1 1 0 0 1]
 [0 1 1 1 0 1 1 1]
 [1 0 1 1 1 1 0 1]]
Final Fitness:
[4 4 4 6 7 6 5 5 6 6]


In [5]:

import random

# Knapsack problem parameters
max_weight = 10
items = {
    "item1": {"weight": 1, "value": 15},
    "item2": {"weight": 3, "value": 17},
    "item3": {"weight": 5, "value": 10},
    "item4": {"weight": 7, "value": 22},
    "item5": {"weight": 9, "value": 18},
}

# Genetic algorithm parameters
population_size = 10
generations = 100
mutation_rate = 0.2

def initialize_population(size):
    return [[random.choice([0, 1]) for _ in range(len(items))] for _ in range(size)]

def fitness(individual):
    total_weight = sum(items[key]["weight"] for key, bit in zip(items, individual) if bit)
    total_value = sum(items[key]["value"] for key, bit in zip(items, individual) if bit)
    return total_value if total_weight <= max_weight else 0

def crossover(parent1, parent2):
    crossover_point = random.randint(1, len(parent1) - 1)
    child = parent1[:crossover_point] + parent2[crossover_point:]
    return child

def mutate(individual):
    mutated_index = random.randint(0, len(individual) - 1)
    individual[mutated_index] = 1 - individual[mutated_index]
    return individual

def genetic_algorithm():
    population = initialize_population(population_size)

    for generation in range(generations):
        population = sorted(population, key=fitness, reverse=True)[:population_size]

        new_population = []

        for _ in range(population_size // 2):
            parent1 = random.choice(population)
            parent2 = random.choice(population)

            child1 = crossover(parent1, parent2)
            child2 = crossover(parent2, parent1)

            if random.random() < mutation_rate:
                child1 = mutate(child1)
            if random.random() < mutation_rate:
                child2 = mutate(child2)

            new_population.extend([child1, child2])

        population = new_population

    best_solution = max(population, key=fitness)
    best_fitness = fitness(best_solution)

    return best_solution, best_fitness

best_solution, best_fitness = genetic_algorithm()

print("Best solution:", best_solution)
print("Best fitness:", best_fitness)




Best solution: [1, 1, 1, 0, 0]
Best fitness: 42


Explanation:

The provided Python code implements a genetic algorithm to tackle the knapsack problem, a classic optimization challenge. The algorithm begins by defining the problem parameters, such as the maximum weight allowed and a list of items with associated weights and values. Individuals in the population are represented as binary strings, indicating whether an item is selected or not. The fitness of each individual is evaluated based on the total value of selected items while penalizing solutions exceeding the weight limit. The algorithm iteratively evolves the population through tournament selection, single-point crossover, and mutation over a specified number of generations. The best individual in each generation, along with its fitness, is tracked and printed. Finally, the algorithm returns the best solution found, showcasing the optimal combination of items and its associated fitness. Users can customize the code for different instances of the knapsack problem by adjusting problem parameters and operators accordingly.